#!/bin/bash

updates_verify() {
	pm_updates=$(pacman -Qu)
	aur_updates=$(yaourt -Qua | grep aur)
	updates=${pm_updates}${aur_updates}
}

sudo pacman -Syy
updates_verify

[[ -z "$updates" ]] && echo -e "\nNo news updates yet."; exit

if [[ "$pm_updates" ]]; then
	echo -e "\n:: Current updates:"
	echo -e "\n$pm_updates\n"
	sudo pacman -Su
fi

if [[ "$aur_updates" ]]; then
	echo -e "\n:: Initializing the update of AUR packs...\n"
	yaourt -Sua
fi

updates_verify
[[ -z "$updates" ]] && exit 1

echo -e "\n:: Removing the old packs of cache...\n"
sudo pacman -Sc

echo -e "\nThe update was completed."

exit